# A Perceptron for Iris_datasets


In [84]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score  

Load relative datasets

In [85]:
iris=datasets.load_iris()
print (iris.data[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


Show the Iris data's features

In [86]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


Show the class of every flower.(0:Setosa,1:Versicolour,2:Virginica)

In [156]:
x=iris.data
y = iris.target
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3,random_state=0)
sc=StandardScaler()
sc.fit(x_train)#计算样本的均值和标准差
x_train_std=sc.transform(x_train)
x_test_std=sc.transform(x_test)

Pclf=Perceptron(n_iter=40,eta0=0.1,random_state=0,max_iter=5,tol=None)#迭代次数、学习速率、重排训练集
Pclf.fit(x_train_std,y_train)

c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:152: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)


Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=0.1,
      fit_intercept=True, max_iter=5, n_iter=40, n_iter_no_change=5,
      n_jobs=None, penalty=None, random_state=0, shuffle=True, tol=None,
      validation_fraction=0.1, verbose=0, warm_start=False)

In [157]:
y_pred=Pclf.predict(x_test)
print ('Accuracy:%.2f' %accuracy_score(y_test,y_pred))

Accuracy:0.40
